/*
 * Copyright 2007 Matthias Hopf <mhopf@suse.de>
 *
 * AtomBIOS disassembler + data structure dumper
 *
 * datastructs.h:
 * Data structure dumpers (actual dumper code autogenerated from _factory.pl).
 *
 * License: to be determined
 */

#ifndef DATASTRUCTS_H_
#define DATASTRUCTS_H_

extern int (*data_dumpers[]) (uint8_t *data, int indent);

#endif
