/*
 * Copyright 2007 Matthias Hopf <mhopf@suse.de>
 *
 * AtomBIOS disassembler + data structure dumper
 *
 * datastructs.c:
 * Data structure dumpers (actual dumper code autogenerated from _factory.pl).
 *
 * License: to be determined
 */

#include <stdio.h>
#include <stdint.h>

#include "datastructs.h"

#include "atombios_types.h"
#include "atombios.h"


const char *space = "                                        ";
#define IND(x)  (&space[50-2*((x)>25?25:(x))])
#define FILL(x) (&space[((x)>50?50:(x))])


#include "datastructs_gen.c"


int (*data_dumpers[]) (uint8_t *data, int indent) = {
    NULL, ATOM_MULTIMEDIA_CAPABILITY_INFO_dumper,
    ATOM_MULTIMEDIA_CONFIG_INFO_dumper, ATOM_STANDARD_VESA_TIMING_dumper,
    ATOM_FIRMWARE_INFO_dumper, ATOM_DAC_INFO_dumper, ATOM_LVDS_INFO_dumper,
    ATOM_TMDS_INFO_dumper, ATOM_ANALOG_TV_INFO_dumper,
    ATOM_SUPPORTED_DEVICES_INFO_dumper, ATOM_GPIO_I2C_INFO_dumper,
    ATOM_VRAM_USAGE_BY_FIRMWARE_dumper, ATOM_GPIO_PIN_LUT_dumper,
    ATOM_VESA_TO_INTENAL_MODE_LUT_dumper, // Typo
    ATOM_COMPONENT_VIDEO_INFO_dumper,
    ATOM_POWERPLAY_INFO_dumper, COMPASSIONATE_DATA_dumper,
    NULL /*ATOM_SAVE_RESTORE_INFO_dumper*/, NULL /*ATOM_PPLL_SS_INFO_dumper*/,
    ATOM_OEM_INFO_dumper, ATOM_XTMDS_INFO_dumper, NULL /*ATOM_MCLK_SS_INFO_dumper*/,
    ATOM_OBJECT_HEADER_dumper, INDIRECT_IO_ACCESS_dumper,
    NULL /*ATOM_MC_INIT_PARAMETER_dumper*/, NULL /*ATOM_ASIC_VDDC_INFO_dumper*/,
    ATOM_ASIC_INTERNAL_SS_INFO_dumper, NULL /*ATOM_TV_VIDEO_MODE_dumper*/,
    ATOM_VRAM_INFO_V3_dumper, ATOM_MEMORY_TRAINING_INFO_dumper,
    ATOM_INTEGRATED_SYSTEM_INFO_dumper, ATOM_ASIC_PROFILING_INFO_dumper,
    ATOM_VOLTAGE_OBJECT_INFO_dumper, ATOM_POWER_SOURCE_INFO_dumper
} ;
